// <auto-generated />
using System;
using CursorsDesktop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CursorsDesktop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260902081538_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("CursorsDesktop.Models.CursorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathToIcon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathToPreview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("TypeId");

                    b.ToTable("Cursors");
                });

            modelBuilder.Entity("CursorsDesktop.Models.CursorTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SystemRole")
                        .IsUnique();

                    b.ToTable("CursorTypes");
                });

            modelBuilder.Entity("CursorsDesktop.Models.PackageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathToPreview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageName")
                        .IsUnique();

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("CursorsDesktop.Models.CursorModel", b =>
                {
                    b.HasOne("CursorsDesktop.Models.PackageModel", "Package")
                        .WithMany("Cursors")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CursorsDesktop.Models.CursorTypeModel", "CursorType")
                        .WithMany("Cursors")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CursorType");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("CursorsDesktop.Models.CursorTypeModel", b =>
                {
                    b.Navigation("Cursors");
                });

            modelBuilder.Entity("CursorsDesktop.Models.PackageModel", b =>
                {
                    b.Navigation("Cursors");
                });
#pragma warning restore 612, 618
        }
    }
}
