// <auto-generated />
using System;
using CursorsDesktop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CursorsDesktop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260901135802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("CursorsDesktop.Models.CursorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathToIcon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathToPreview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("TypeId");

                    b.ToTable("Cursors");
                });

            modelBuilder.Entity("CursorsDesktop.Models.CursorTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SystemRole")
                        .IsUnique();

                    b.ToTable("CursorTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default Pointer",
                            SystemRole = "Arrow"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Help",
                            SystemRole = "Help"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Working in Background",
                            SystemRole = "AppStarting"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Busy",
                            SystemRole = "Wait"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Precision Select",
                            SystemRole = "Crosshair"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Text Selection",
                            SystemRole = "IBeam"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Handwriting",
                            SystemRole = "NWPen"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Not Allowed",
                            SystemRole = "No"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Resize Vertical",
                            SystemRole = "SizeNS"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Resize Horizontal",
                            SystemRole = "SizeWE"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Diagonal Resize 1",
                            SystemRole = "SizeNWSE"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Diagonal Resize 2",
                            SystemRole = "SizeNESW"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Move",
                            SystemRole = "SizeAll"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Alternate Select",
                            SystemRole = "UpArrow"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Link Select",
                            SystemRole = "Hand"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Location Select",
                            SystemRole = "Pin"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Person Select",
                            SystemRole = "Person"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Auto-scroll (All Directions)",
                            SystemRole = "PanAll"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Auto-scroll (North-South)",
                            SystemRole = "PanNS"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Auto-scroll (West-East)",
                            SystemRole = "PanWE"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Auto-scroll (North)",
                            SystemRole = "PanN"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Auto-scroll (South)",
                            SystemRole = "PanS"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Auto-scroll (West)",
                            SystemRole = "PanW"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Auto-scroll (East)",
                            SystemRole = "PanE"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Auto-scroll (North West)",
                            SystemRole = "PanNW"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Auto-scroll (North East)",
                            SystemRole = "PanNE"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Auto-scroll (South West)",
                            SystemRole = "PanSW"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Auto-scroll (South East)",
                            SystemRole = "PanSE"
                        },
                        new
                        {
                            Id = 29,
                            Name = "CD Auto-run",
                            SystemRole = "CD"
                        });
                });

            modelBuilder.Entity("CursorsDesktop.Models.PackageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathToPreview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageName")
                        .IsUnique();

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("CursorsDesktop.Models.CursorModel", b =>
                {
                    b.HasOne("CursorsDesktop.Models.PackageModel", "Package")
                        .WithMany("Cursors")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CursorsDesktop.Models.CursorTypeModel", "CursorType")
                        .WithMany("Cursors")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CursorType");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("CursorsDesktop.Models.CursorTypeModel", b =>
                {
                    b.Navigation("Cursors");
                });

            modelBuilder.Entity("CursorsDesktop.Models.PackageModel", b =>
                {
                    b.Navigation("Cursors");
                });
#pragma warning restore 612, 618
        }
    }
}
